spring:
  application:
    name: market-app

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: market-app-client
            client-secret: sVnUrlE1Zt7KMdifhiYaskKFDCRUIXPj
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/market-realm/protocol/openid-connect/token

server:
  port: 8080

payment:
  service:
    url: http://localhost:8081

logging:
  level:
    com.example.mymarketapp: DEBUG
    org.springframework.data.redis: DEBUG