version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8180
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8180:8180"
    networks:
      - market-network

  redis:
    image: redis:7-alpine
    container_name: market-redis
    ports:
      - "6379:6379"
    networks:
      - market-network

  postgres:
    image: postgres:15-alpine
    container_name: market-postgres
    environment:
      POSTGRES_DB: market_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - market-network

networks:
  market-network:
    driver: bridge

volumes:
  postgres-data:
