DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255)
);

CREATE TABLE items (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255),
                       description VARCHAR(2000),
                       img_path VARCHAR(512),
                       price BIGINT
);

CREATE TABLE carts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id BIGINT NOT NULL,
                       CONSTRAINT fk_carts_users FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE cart_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            cart_id BIGINT NOT NULL,
                            item_id BIGINT NOT NULL,
                            title VARCHAR(255),
                            description VARCHAR(2000),
                            img_path VARCHAR(512),
                            price BIGINT,
                            count INT,
                            CONSTRAINT fk_cart_items_carts FOREIGN KEY (cart_id) REFERENCES carts (id)
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        total_sum BIGINT
);

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             item_id BIGINT NOT NULL,
                             title VARCHAR(255),
                             price BIGINT,
                             count INT,
                             CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) REFERENCES orders (id)
);