spring:
  application:
    name: payment-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/market-realm

server:
  port: 8081

payment:
  initial:
    balance: 200000

logging:
  level:
    com.example.paymentservice: DEBUG
    org.springframework.web: DEBUG